### ISSUE TITLE
cookie失效

### ISSUE THREAD

**Issue by ZEKEOO** [wyt1215819315/autoplan#10]
包含cookie_token和account_id字段的米游社cookie无法获取。
试了bbs.mihoyo.com和bbs.mihoyo.com/ys，cookie都不含cookie_token和account_id

**Comment by wyt1215819315** [comment]
> 包含cookie_token和account_id字段的米游社cookie无法获取。 试了bbs.mihoyo.com和bbs.mihoyo.com/ys，cookie都不含cookie_token和account_id

退出重新登陆试试

**Comment by ZEKEOO** [comment]
感谢，重登之后正常了
