### ISSUE TITLE
新版3.0 自建，sqlite配置，为什么定时任务不触发

### ISSUE THREAD

**Issue by yangbinbin9527** [wyt1215819315/autoplan#106]
新版3.0 自建，sqlite配置，为什么定时任务不触发
![image](https://github.com/wyt1215819315/autoplan/assets/39398221/cb7d5cba-73f5-4af3-b170-3b6909a51ad9)
都是我手动点的触发的

**Comment by yangbinbin9527** [comment]
![image](https://github.com/wyt1215819315/autoplan/assets/39398221/7cadf521-9b11-4510-9617-9c996284ba65)
sqlite里初始的配置

**Comment by yangbinbin9527** [comment]
观察2天了

**Comment by yangbinbin9527** [comment]
不是docker部署，是release上下的包，直接部署再服务器上的

**Comment by wyt1215819315** [comment]
新版之前的包有bug的，我自己测试服务器上的已经修了，版本是3.0.8-dev

**Comment by wyt1215819315** [comment]
前端也需要更新的，定时任务里面开关状态值反了

**Comment by yangbinbin9527** [comment]
额，我昨天下的最新的3.08部署的

**Comment by yangbinbin9527** [comment]
sqlite db用的之前的，就替换了 auto_plan.jar 配置文件，和前端项目

**Comment by yangbinbin9527** [comment]
ok了，sqlite db删了，重新初始化了个
