### ISSUE TITLE
Docker Compose更新

### ISSUE THREAD

**Issue by jx9468** [wyt1215819315/autoplan#108]
Docker Compose部署的还是老版本UI，docker compose pull拉取的最新镜像就是老版😂是没有更新吗，我看demo和其他人issues的UI都是新的🤦‍♂️
![3c61a324a9d7ff377466ece8e35b909](https://github.com/wyt1215819315/autoplan/assets/78193384/de1d03cb-c7b4-463c-ab13-a3b6652affad)

**Comment by jx9468** [comment]
日志输出密码六位数，面板要求密码八位数😂绷不住了🤦‍♂️
![aa](https://github.com/wyt1215819315/autoplan/assets/78193384/b0a7b312-f0ab-4320-8371-3df2c7c49de3)
![bb](https://github.com/wyt1215819315/autoplan/assets/78193384/40013d39-7537-4ec4-b795-18cfea7e2800)

**Comment by yanisCC** [comment]
密码问题已提交Pull request.
https://github.com/wyt1215819315/autoplan/pull/110

**Comment by jx9468** [comment]
Docker Hub上的版本还是16天前的麻烦大佬更新一下，十分感谢😆
