### ISSUE TITLE
我fork了你的项目，并对米游社原神签到部分进行了一些修改

### ISSUE THREAD

**Issue by MuXia-0326** [wyt1215819315/autoplan#16]
主要改的内容是
修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示

**Comment by wyt1215819315** [comment]
可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）


> 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示

**Comment by MuXia-0326** [comment]
> 可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）
> 
> > 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示

本来还想改下页面的，但用的freemarker模板语法太多了，我一般用的是js的形式，不是很好改，就没改了

**Comment by wyt1215819315** [comment]
> > 可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）
> > > 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示
> 
> 本来还想改下页面的，但用的freemarker模板语法太多了，我一般用的是js的形式，不是很好改，就没改了

我页面确实做挺丑的，vue不怎么会，就用了layui，前后端并没有完全分离
然后刚写完一个月layui倒闭了.....
重做页面的话，也懒得动了，反正属于能看就行的那种

**Comment by MuXia-0326** [comment]
> > > 可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）
> > > > 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示
> > 
> > 
> > 本来还想改下页面的，但用的freemarker模板语法太多了，我一般用的是js的形式，不是很好改，就没改了
> 
> 我页面确实做挺丑的，vue不怎么会，就用了layui，前后端并没有完全分离 然后刚写完一个月layui倒闭了..... 重做页面的话，也懒得动了，反正属于能看就行的那种

layui也挺好的，主站没了还有镜像站，主要是没前后端分离，不是很好去改，不然我可以帮你改成iframe版的，那样会好看很多

**Comment by wyt1215819315** [comment]
> > > > 可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）
> > > > > 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示
> > > 
> > > 
> > > 本来还想改下页面的，但用的freemarker模板语法太多了，我一般用的是js的形式，不是很好改，就没改了
> > 
> > 
> > 我页面确实做挺丑的，vue不怎么会，就用了layui，前后端并没有完全分离 然后刚写完一个月layui倒闭了..... 重做页面的话，也懒得动了，反正属于能看就行的那种
> 
> layui也挺好的，主站没了还有镜像站，主要是没前后端分离，不是很好去改，不然我可以帮你改成iframe版的，那样会好看很多

那我做下分离吧，改一下不难，
还有mybatis的一大堆xml，可以换成mybatis-plus精简一下
过几天有空的时候我改下

**Comment by MuXia-0326** [comment]
> > > > > 可以新建一个分支，提交下pr，我之前做的时候确实没考虑多个角色多个服务器的问题（偷懒）
> > > > > > 主要改的内容是 修改米游社原神签到逻辑，适配米游社账号下多角色不同服的签到处理，并修改一些页面显示
> > > > 
> > > > 
> > > > 本来还想改下页面的，但用的freemarker模板语法太多了，我一般用的是js的形式，不是很好改，就没改了
> > > 
> > > 
> > > 我页面确实做挺丑的，vue不怎么会，就用了layui，前后端并没有完全分离 然后刚写完一个月layui倒闭了..... 重做页面的话，也懒得动了，反正属于能看就行的那种
> > 
> > 
> > layui也挺好的，主站没了还有镜像站，主要是没前后端分离，不是很好去改，不然我可以帮你改成iframe版的，那样会好看很多
> 
> 那我做下分离吧，改一下不难， 还有mybatis的一大堆xml，可以换成mybatis-plus精简一下 过几天有空的时候我改下

嗯，等你改好了，我在帮你改改页面

**Comment by wyt1215819315** [comment]
> 

好的 感谢大佬

**Comment by MuXia-0326** [comment]
> 

我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下

**Comment by wyt1215819315** [comment]
> > 
> 
> 我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下

嗯，我也刚刚毕业呐，现在已经在公司实习了，干的是后端，所以前端不咋会

**Comment by MuXia-0326** [comment]
> > > 
> > 
> > 
> > 我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下
> 
> 嗯，我也刚刚毕业呐，现在已经在公司实习了，干的是后端，所以前端不咋会

我也是后端，但公司没前端只能硬上，被迫学会了

**Comment by MuXia-0326** [comment]
> > > 
> > 
> > 
> > 我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下
> 
> 嗯，我也刚刚毕业呐，现在已经在公司实习了，干的是后端，所以前端不咋会

后台代码还有很大的提升空间啊，我看了一下手动调用定时任务的代码，我在我fork的项目下改了一下，你可以参考参考

**Comment by wyt1215819315** [comment]
> > > > 
> > > 
> > > 
> > > 我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下
> > 
> > 
> > 嗯，我也刚刚毕业呐，现在已经在公司实习了，干的是后端，所以前端不咋会
> 
> 后台代码还有很大的提升空间啊，我看了一下手动调用定时任务的代码，我在我fork的项目下改了一下，你可以参考参考

嗯，工作之前写的代码了，东拼西凑的，有些地方我现在自己都看不懂

**Comment by MuXia-0326** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我不是啥大佬，也是刚毕业的小萌新，对了，分支请求发起了，你有时间看看合并一下
> > > 
> > > 
> > > 嗯，我也刚刚毕业呐，现在已经在公司实习了，干的是后端，所以前端不咋会
> > 
> > 
> > 后台代码还有很大的提升空间啊，我看了一下手动调用定时任务的代码，我在我fork的项目下改了一下，你可以参考参考
> 
> 嗯，工作之前写的代码了，东拼西凑的，有些地方我现在自己都看不懂

确实，杂，定时任务那部分看不太懂，不知道如何实现的，其他的大概能看出个名堂来

**Comment by wyt1215819315** [comment]
> 

定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它

**Comment by MuXia-0326** [comment]
> > 
> 
> 定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它

表单那部分也是扣的吧，看ui跟原版的layui差别挺大的，其实定时任务可以用简单一点的方法实现，不过就是不能控制台设置罢了，我刚刚又看了一下，没明白添加为什么不需要调用他那个工具类，修改删除的都调用了，开启定时任务像是项目启动的时候读取数据库的配置信息，然后逐个开启定时任务的，或许可以自己造个轮子

**Comment by wyt1215819315** [comment]
> > > 
> > 
> > 
> > 定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它
> 
> 表单那部分也是扣的吧，看ui跟原版的layui差别挺大的，其实定时任务可以用简单一点的方法实现，不过就是不能控制台设置罢了，我刚刚又看了一下，没明白添加为什么不需要调用他那个工具类，修改删除的都调用了，开启定时任务像是项目启动的时候读取数据库的配置信息，然后逐个开启定时任务的，或许可以自己造个轮子

没用springboot那个自带的定时就是因为那个可以自己配置，而不是写死在代码
虽然后来发现原生springboot似乎也可以实现这个，但是嫌麻烦直接copy过来了
他那边用的是quartz的定时任务，我实在理解不了那个玩意

**Comment by MuXia-0326** [comment]
> > > > 
> > > 
> > > 
> > > 定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它
> > 
> > 
> > 表单那部分也是扣的吧，看ui跟原版的layui差别挺大的，其实定时任务可以用简单一点的方法实现，不过就是不能控制台设置罢了，我刚刚又看了一下，没明白添加为什么不需要调用他那个工具类，修改删除的都调用了，开启定时任务像是项目启动的时候读取数据库的配置信息，然后逐个开启定时任务的，或许可以自己造个轮子
> 
> 没用springboot那个自带的定时就是因为那个可以自己配置，而不是写死在代码 虽然后来发现原生springboot似乎也可以实现这个，但是嫌麻烦直接copy过来了 他那边用的是quartz的定时任务，我实在理解不了那个玩意

对比了一下，添加定时任务的时候好像遗漏了开启任务的步骤，只有插入数据库的步骤，在pearadmin里面是有的

**Comment by wyt1215819315** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它
> > > 
> > > 
> > > 表单那部分也是扣的吧，看ui跟原版的layui差别挺大的，其实定时任务可以用简单一点的方法实现，不过就是不能控制台设置罢了，我刚刚又看了一下，没明白添加为什么不需要调用他那个工具类，修改删除的都调用了，开启定时任务像是项目启动的时候读取数据库的配置信息，然后逐个开启定时任务的，或许可以自己造个轮子
> > 
> > 
> > 没用springboot那个自带的定时就是因为那个可以自己配置，而不是写死在代码 虽然后来发现原生springboot似乎也可以实现这个，但是嫌麻烦直接copy过来了 他那边用的是quartz的定时任务，我实在理解不了那个玩意
> 
> 对比了一下，添加定时任务的时候好像遗漏了开启任务的步骤，只有插入数据库的步骤，在pearadmin里面是有的

可以留个联系方式吗，到时候交流交流

**Comment by MuXia-0326** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 定时任务那部分完全从pearadmin里面抠下来的，我没看懂也不敢改它
> > > > 
> > > > 
> > > > 表单那部分也是扣的吧，看ui跟原版的layui差别挺大的，其实定时任务可以用简单一点的方法实现，不过就是不能控制台设置罢了，我刚刚又看了一下，没明白添加为什么不需要调用他那个工具类，修改删除的都调用了，开启定时任务像是项目启动的时候读取数据库的配置信息，然后逐个开启定时任务的，或许可以自己造个轮子
> > > 
> > > 
> > > 没用springboot那个自带的定时就是因为那个可以自己配置，而不是写死在代码 虽然后来发现原生springboot似乎也可以实现这个，但是嫌麻烦直接copy过来了 他那边用的是quartz的定时任务，我实在理解不了那个玩意
> > 
> > 对比了一下，添加定时任务的时候好像遗漏了开启任务的步骤，只有插入数据库的步骤，在pearadmin里面是有的
> 
> 可以留个联系方式吗，到时候交流交流

qq504792896
