### ISSUE TITLE
添加更改通知格式的界面

### ISSUE THREAD

**Issue by Lemonawa** [wyt1215819315/autoplan#26]
毕竟，不是每个人都叫老吴

**Comment by wyt1215819315** [comment]
> 毕竟，不是每个人都叫老吴

下源码自己改就好了，反正我改了也不可能同时满足所有人的

**Comment by Lemonawa** [comment]
> > 毕竟，不是每个人都叫老吴
> 
> 下源码自己改就好了，反正我改了也不可能同时满足所有人的

好的
