### ISSUE TITLE
添加对recaptcha、hcaptcha验证码的支持

### ISSUE THREAD

**Issue by Lemonawa** [wyt1215819315/autoplan#27]
现在的验证码很容易被识别，基本没啥用

**Comment by wyt1215819315** [comment]
就算登录成功也没啥用，反正不返回cookie，那种阴间验证码，看了就血压高

**Comment by Lemonawa** [comment]
多登录几遍低配服务器就炸了

**Comment by MuXia-0326** [comment]
> 多登录几十遍低配服务器就炸了

我们添加验证码就是为了防止多次发送登录请求，但这项目毕竟是小项目，所以就没做更深层次的应对措施，至于你说的两个验证码，现在也可以通过其他手段，进行识别，没有绝对安全的，想要避免这种用户反复登录（准确来说是恶意攻击）的情况，得在登录模块里面写对于的逻辑进行处理，验证码终究只是个验证码

**Comment by Lemonawa** [comment]
> > 多登录几十遍低配服务器就炸了
> 
> 我们添加验证码就是为了防止多次发送登录请求，但这项目毕竟是小项目，所以就没做更深层次的应对措施，至于你说的两个验证码，现在也可以通过其他手段，进行识别，没有绝对安全的，想要避免这种用户反复登录（准确来说是恶意攻击）的情况，得在登录模块里面写对应的逻辑进行处理，验证码终究只是个验证码，想要防护更好，得加钱（加入手机注册或者邮箱注册可以一定程度上避免，但也会有被恶意发送验证码的情况）

好的
