### ISSUE TITLE
大佬有群吗或者QQ我想咨询咨询，我在这一运行CPU拉满然后就自己停了

### ISSUE THREAD

**Issue by MIKU-CL** [wyt1215819315/autoplan#29]
大佬有群吗或者QQ我想咨询咨询，我在这一运行CPU拉满然后就自己停了

**Comment by wyt1215819315** [comment]
> 大佬有群吗或者QQ我想咨询咨询，我在这一运行CPU拉满然后就自己停了

没正常启动吧，启动一瞬间cpu拉满是正常的，停了就是没运行，自己看下运行日志，或者发这里

**Comment by MIKU-CL** [comment]
![Uploading Screenshot_2022-03-08-00-25-40-407_com.android.chrome.jpg…]()

**Comment by wyt1215819315** [comment]
> ![Screenshot_2022-03-08-00-25-22-954_com android chrome](https://user-images.githubusercontent.com/36833022/157075592-3d41b4cd-91c4-4efd-90af-6df51e62df06.jpg)
> 
> ![Screenshot_2022-03-08-00-25-44-453_com android chrome](https://user-images.githubusercontent.com/36833022/157075615-a091b0b2-af68-465d-8760-f2ecf74cf4b9.jpg) 2022/03/07 23:44:03 [error] 13026#0: *817 connect() failed (111: Connection refused) while connecting to upstream, client: 123.114.207.181, server: 124.221.154.234, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:26666/", host: "124.221.154.234" 2022/03/07 23:44:03 [error] 13026#0: *817 connect() failed (111: Connection refused) while connecting to upstream, client: 123.114.207.181, server: 124.221.154.234, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:26666/favicon.ico", host: "124.221.154.234", referrer: "http://124.221.154.234/" 大佬我电脑放教室了委屈您这么看看

没截到关键的，主要是项目日志，nginx的日志没用，看似是mysql的问题

**Comment by wyt1215819315** [comment]
> ![Screenshot_2022-03-08-00-46-22-249_com android chrome](https://user-images.githubusercontent.com/36833022/157079067-acda70e7-ad3c-4ccf-a440-b9b7d009964f.jpg)
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121] at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_121] at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] ... 101 common frames omitted Caused by: java.net.SocketTimeoutException: connect timed out at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121] at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121] at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121] at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121] at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.27.jar!/:8.0.27] ... 104 common frames omitted

阿这，网上说是MySQL什么时间的问题，我之前也碰到过这错不过第二次请求就好了，你百度搜下关键字communications link failed

**Comment by wyt1215819315** [comment]
> 这个我在哪个教程网站里看到了，我明天用哪个方法重新导一下。但是现在的报错应该和少表没关系吧？我搜了是说什么太长时间没链接数据库自动断开了，我看百度上说是默认8小时，但我总共从开始才两个小时

反正这个报错和项目本身没多大关系，我这边目前没这个问题，你要解决的话可以尝试百度上的方法

**Comment by MIKU-CL** [comment]
大佬配置文件的url就改那两个地方就行了吗，一个地址一个数据库名，数据库端口号需要改或者设置吗。还有后面那么一长串就默认那样吗
