### ISSUE TITLE
老哥我在maven打包的时候发现显示找不到该符号misc

### ISSUE THREAD

**Issue by JustinChris-freshman** [wyt1215819315/autoplan#3]
能问一下是怎么回事吗

**Comment by wyt1215819315** [comment]
> 能问一下是怎么回事吗

具体在哪个文件报的错，可以截张图

**Comment by JustinChris-freshman** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月12日(星期天) 凌晨0:49
收件人: ***@***.***&gt;; 
抄送: "Junheng ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wyt1215819315/autoplan] 老哥我在maven打包的时候发现显示找不到该符号misc (#3)





  
能问一下是怎么回事吗
  
具体在哪个文件报的错，可以截张图
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JustinChris-freshman** [comment]
[https://s3.bmp.ovh/imgs/2021/09/07f51a3e60282b6a.png](url)

**Comment by JustinChris-freshman** [comment]
https://s3.bmp.ovh/imgs/2021/09/07f51a3e60282b6a.png

**Comment by wyt1215819315** [comment]
这个应该是jdk版本的问题，你用1.8试试

**Comment by JustinChris-freshman** [comment]
好的，我重新试试

**Comment by JustinChris-freshman** [comment]
成功了，感谢大佬
https://s3.bmp.ovh/imgs/2021/09/3b1088c11d6885f5.png
