### ISSUE TITLE
发送了无效的响应

### ISSUE THREAD

**Issue by zoffyultraman** [wyt1215819315/autoplan#30]
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/18696463/157380665-916cc160-e067-4a34-a842-e0fcbca3f65e.png">
点击登陆后
<img width="917" alt="image" src="https://user-images.githubusercontent.com/18696463/157380805-a1a150f3-a94b-4921-9270-7433abfbffa0.png">
更改为http后无法访问

**Comment by zoffyultraman** [comment]
系统CentOS Linux release 7.8.2003 (Core)
jdk:open-jdk1.8

**Comment by zoffyultraman** [comment]
下载releases版本无这个问题
下载action里面构建的有这个问题

**Comment by MuXia-0326** [comment]
这个应该是在请求头里面设置了https转发的原因，稍后发布两个版本吧
