### ISSUE TITLE
米游社讨论区签到提示失败

### ISSUE THREAD

**Issue by MIKU-CL** [wyt1215819315/autoplan#32]
![2MN{6SEW938MH~`I1}8OT9N](https://user-images.githubusercontent.com/36833022/157406866-c56ddb25-2d7a-48e3-9cf0-7ffe23c7d1c3.png)
![15DBCB6F59069751FA6EC33B4416BBBC](https://user-images.githubusercontent.com/36833022/157407180-5edb496b-c700-4fda-bd04-bf4fe7cdeb10.png)
![774E52B7DC8A285C65539760CB7C102A](https://user-images.githubusercontent.com/36833022/157407249-c6801860-ad57-4bda-b9f8-03bcdfa2bdf8.png)
我改了cron执行表达式改成每天0：5分执行的，不存在说我重复签到。在米游币列表看社区签到是成功的，但在查看经验的地方，一个都没签

**Comment by MuXia-0326** [comment]
在获取帖子的时候进行了签到操作，下面又反复进行了操作，这是正常的提示
