### ISSUE TITLE
B站任务创建后一直为关闭状态

### ISSUE THREAD

**Issue by Moke-Mo** [wyt1215819315/autoplan#34]
可以手动执行并且执行成功，但是任务状态一直是关闭

**Comment by MuXia-0326** [comment]
希望提供一下版本和截图，可能是老版本的页面显示问题

**Comment by wyt1215819315** [comment]
> 可以手动执行并且执行成功，但是任务状态一直是关闭

新版已修复，测试服务器已经更新，添加页面的状态反了，忘记改过来了，编辑页面是好的
