### ISSUE TITLE
7.7版本的宝塔应该怎么部署

### ISSUE THREAD

**Issue by Eternity-luo** [wyt1215819315/autoplan#35]
大佬，能出个怎么在7.7宝塔的部署项目的方式吗😂

**Comment by MuXia-0326** [comment]
个人不用宝塔，不会宝塔的部署方式

**Comment by MuXia-0326** [comment]
https://www.iculture.cc/knowledge/pig=10061
这是别人出的教程，我不是作者，你可以参考快看

**Comment by Eternity-luo** [comment]
> https://www.iculture.cc/knowledge/pig=10061 这是别人出的教程，我不是作者，你可以参考快看

好的，谢谢
