### ISSUE TITLE
任务添加请求&BUG反馈

### ISSUE THREAD

**Issue by Mortal520** [wyt1215819315/autoplan#40]
希望网易云签到能集成云豆任务及音乐人任务
网易云签到项目地址https://github.com/chen310/NeteaseCloudMusicTasks

AUTO_PLAN网页手机端尝试bilibili扫码登录时，二维码过大显示不全，无法正常使用
如图：
![Uploading )AH4IO(3F%@7G}TURVOZO)H.jpg…]()

**Comment by Mortal520** [comment]
![)AH4IO(3F%@7G}TURVOZO)H](https://user-images.githubusercontent.com/72114014/159713711-50000880-2fee-401c-9c7a-130f177bd499.jpg)

**Comment by MuXia-0326** [comment]
最新的2.3版本修复了二维码的显示问题
