### ISSUE TITLE
mysql 用的那个版本 

### ISSUE THREAD

**Issue by qingcong** [wyt1215819315/autoplan#54]
Specified key was too long; max key length is 767 bytes

 1067 - Invalid default value for 'date'

两个错误 弄了半天没弄好

**Comment by Mateoust** [comment]
我使用的是`Mysql 8.0.23`是没有问题的，仅供参考

**Comment by qingcong** [comment]
> 我使用的`Mysql 8.0.23`是没有问题的，翻译参考

我装的5.5 服务器本地都执行错误，可能是版本老吧

**Comment by MuXia-0326** [comment]
复制sql文件里面的内容在可视化工具里面导入试试，我测试是正常的，数据库编码格式选择utf8

**Comment by qingcong** [comment]
> 复制sql文件里面的内容在可视化工具里面导入试试，我测试是正常的，数据库编码格式选择utf8

已解决，升级数据库
