### ISSUE TITLE
前端的样式和JS cdn挂了 把cdn.jsdelivr.net换成fastly.jsdelivr.net 

### ISSUE THREAD

**Issue by hqw567** [wyt1215819315/autoplan#59]
![image](https://user-images.githubusercontent.com/74847198/170061278-68d0e058-8fe6-4475-adce-6f08619fe4d2.png)
![image](https://user-images.githubusercontent.com/74847198/170061295-e33ba1bf-9041-4abd-accb-e557f478962d.png)
![image](https://user-images.githubusercontent.com/74847198/170062085-d36ecf24-ebaf-486b-bc88-f01936aef1e1.png)

https://github.com/jsdelivr/jsdelivr/issues/18397 @wyt1215819315

**Comment by EA1973** [comment]
你好，请问在哪里更改，刚接触不太会。

**Comment by wyt1215819315** [comment]
> ![image](https://user-images.githubusercontent.com/74847198/170061278-68d0e058-8fe6-4475-adce-6f08619fe4d2.png) ![image](https://user-images.githubusercontent.com/74847198/170061295-e33ba1bf-9041-4abd-accb-e557f478962d.png) ![image](https://user-images.githubusercontent.com/74847198/170062085-d36ecf24-ebaf-486b-bc88-f01936aef1e1.png)
> 
> [jsdelivr/jsdelivr#18397](https://github.com/jsdelivr/jsdelivr/issues/18397) @wyt1215819315

已修复
