### ISSUE TITLE
你好，哔哩哔哩投币逻辑问题

### ISSUE THREAD

**Issue by Rashhz** [wyt1215819315/autoplan#6]
发现同一个账号在投币时经常会去投之前投过币的视频，导致投币多次失败，投币过程结束，可以不可以优化一下投币的逻辑？

**Comment by wyt1215819315** [comment]
> 发现同一个账号在投币时经常会去投之前投过币的视频，导致投币多次失败，投币过程结束，可以不可以优化一下投币的逻辑？

看了眼代码，个人认为写的没毛病，我本地测试也没问题，但是服务端之前确实是存在这个问题的，如果现在还是这样你就尝试切换下优先投币设置看看，优先up模式的话可以多关注些up防止刷到重复的内容

**Comment by Rashhz** [comment]
切换到热门投币确实就解决了，感谢
