### ISSUE TITLE
新版本下载不了了

### ISSUE THREAD

**Issue by wdxbbj** [wyt1215819315/autoplan#64]
下载时如图
![image](https://user-images.githubusercontent.com/84279524/171591256-4f1b2010-bd0e-4a48-8685-4356aad422b0.png)

**Comment by MuXia-0326** [comment]
如果是不能下载jar包的话，或许你可以反馈给github官方
如果是其他的东西不能下载，请描述详细一些

**Comment by MuXia-0326** [comment]
> 下载时如图 ![image](https://user-images.githubusercontent.com/84279524/171591256-4f1b2010-bd0e-4a48-8685-4356aad422b0.png)

https://superuser.com/questions/1438611/how-to-solve-fastly-error-unknown-domain
参考一下这个解决办法
