### ISSUE TITLE
米游社签到失败

### ISSUE THREAD

**Issue by Eternity-luo** [wyt1215819315/autoplan#68]
签到不了了，能修吗？

**Comment by MuXia-0326** [comment]
你这个问题，已经更新代码解决了
如果你是自己部署项目的话，更新代码就行了
如果你是用的演示站，可能演示站的代码还没更新

**Comment by MuXia-0326** [comment]
已经发布新版本[2.6](https://github.com/wyt1215819315/autoplan/releases/tag/v2.6)
