### ISSUE TITLE
弹窗右上角的×不显示，米游社添加任务边上图标不显示

### ISSUE THREAD

**Issue by MIKU-CL** [wyt1215819315/autoplan#69]
![image](https://user-images.githubusercontent.com/36833022/183293148-a19545f0-e760-4eb2-9fe9-8ab774277d30.png)

**Comment by yemaxul** [comment]
那是因为你把电脑字体做了缩放吧，用ctrl+滚轮缩小一点就行

**Comment by yemaxul** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/62631141/183466542-e4ffa6c0-76fd-4002-ae9e-5720e3257e10.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/62631141/183466643-cd7f6b67-7609-4d00-8e16-0003e4408dc7.png">
你看看情况是不是这样

**Comment by MuXia-0326** [comment]
> ![image](https://user-images.githubusercontent.com/36833022/183293148-a19545f0-e760-4eb2-9fe9-8ab774277d30.png)

看上方按钮的样式可能是js文件没加载完全，刷新让js文件加载完全应该能解决
