### ISSUE TITLE
原神签到福利签到失败：尚未登录

### ISSUE THREAD

**Issue by Lkhsss** [wyt1215819315/autoplan#70]
`
原神签到福利签到失败：尚未登录
null`
请问能修复吗

**Comment by yemaxul** [comment]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/62631141/183466884-3873ea6d-b3fe-45cd-82e2-d66416322e27.png">
我是签到不成功，但是是能获取返回的信息，8月8就没有签到，8/9 0.15分添加通行证ck，也是签到失败，但是其他成功了，楼主你的ck是不是失效了，有检查过吗？

**Comment by yemaxul** [comment]
个人感觉是老米改api了，小白，说错勿喷doge

**Comment by MuXia-0326** [comment]
> ` 原神签到福利签到失败：尚未登录 null` 请问能修复吗

你这种情况应该是cookie失效了，重新配置cookie

**Comment by MuXia-0326** [comment]
> <img alt="image" width="213" src="https://user-images.githubusercontent.com/62631141/183466884-3873ea6d-b3fe-45cd-82e2-d66416322e27.png">
> 
> 我是签到不成功，但是是能获取返回的信息，8月8就没有签到，8/9 0.15分添加通行证ck，也是签到失败，但是其他成功了，楼主你的ck是不是失效了，有检查过吗？

你这个问题，已经更新代码解决了，如果你是自己部署项目的话，更新代码就行了，如果你是用的演示站，可能演示站的代码还没更新

**Comment by MuXia-0326** [comment]
已经发布新版本[2.6](https://github.com/wyt1215819315/autoplan/releases/tag/v2.6)
