### ISSUE TITLE
Bilibili任务执行状态与实际不匹配

### ISSUE THREAD

**Issue by Lemonawa** [wyt1215819315/autoplan#72]
如图
![图片](https://user-images.githubusercontent.com/69106050/184144696-bd4a28c1-5330-42dd-8f62-4bfa7836a117.png)
实际已运行成功，面板仍显示失败

**Comment by MuXia-0326** [comment]
新版哔哩哔哩任务只要有一个功能点失败，就会显示运行失败
你这里失败是因为
![image](https://user-images.githubusercontent.com/63834850/184264477-61569f44-2ac6-4ab7-a3c0-868c0eeca46d.png)

总的来说影响不大

**Comment by Lemonawa** [comment]
> 新版哔哩哔哩任务只要有一个功能点失败，就会显示运行失败 你这里失败是因为 ![image](https://user-images.githubusercontent.com/63834850/184264477-61569f44-2ac6-4ab7-a3c0-868c0eeca46d.png)
> 
> 总的来说影响不大

确实影响不大，整个任务也能正常运行，但是面板上的信息也同时会显示错误
比如今天的运行结果：
![图片](https://user-images.githubusercontent.com/69106050/184272261-3dcdbb2d-745d-45a1-9c68-bf9c2ead2c73.png)

**Comment by MuXia-0326** [comment]
> > 新版哔哩哔哩任务只要有一个功能点失败，就会显示运行失败 你这里失败是因为 ![image](https://user-images.githubusercontent.com/63834850/184264477-61569f44-2ac6-4ab7-a3c0-868c0eeca46d.png)
> > 总的来说影响不大
> 
> 确实影响不大，整个任务也能正常运行，但是面板上的信息也同时会显示错误 比如今天的运行结果： ![图片](https://user-images.githubusercontent.com/69106050/184272261-3dcdbb2d-745d-45a1-9c68-bf9c2ead2c73.png)

这个日志里面的硬币剩余量是开始执行的时候的硬币剩余量，而页面上显示的是执行完任务后的硬币剩余量，你现在这情况可能是更新数据库记录的时候失败了

**Comment by MuXia-0326** [comment]
我刚刚看了下代码，投币的硬币扣除视乎是忘记记录变化值，但银瓜子换硬币的添加记录却又记录下来了，所以会出现硬币变多的情况，但你日志显示，银瓜子余额不足，所以很大概率是更新数据库的时候失败了，你自己结合日志看看是不是我说的这种情况吧

**Comment by Lemonawa** [comment]
没错，数据库是49.8

**Comment by Lemonawa** [comment]
但是执行日志更新到了今天的

**Comment by MuXia-0326** [comment]
> 但是执行日志更新到了今天的，说明数据库连接没问题

我是指看项目的后台执行日志，看下update操作是成功还是报错

**Comment by Lemonawa** [comment]
> > 但是执行日志更新到了今天的，说明数据库连接没问题
> 
> 我是指看项目的后台执行日志，看下update操作是成功还是报错

成功

**Comment by MuXia-0326** [comment]
那你现在实际硬币数是多少

**Comment by Lemonawa** [comment]
> 那你现在实际硬币数是多少

实际为日志中的14.8

**Comment by MuXia-0326** [comment]
来个联系方式，这样聊太费劲了

**Comment by Lemonawa** [comment]
> 来个联系方式，这样聊太费劲了

t.me/Lemonawa
