### ISSUE TITLE
如何配置米游社其他游戏签到

### ISSUE THREAD

**Issue by EvilMir** [wyt1215819315/autoplan#73]
如何配置米游社其他游戏签到，比如崩坏3

**Comment by MuXia-0326** [comment]
本项目不支持米游社除原神外的其他游戏签到
如果你会java代码的话，可以参考其他项目对本项目进行拓展
如果你不会的话，可以考虑使用其他项目进行签到领取

**Comment by EvilMir** [comment]
> 本项目不支持米游社除原神外的其他游戏签到 如果你会java代码的话，可以参考其他项目对本项目进行拓展 如果你不会的话，可以考虑使用其他项目进行签到领取

我看里面都有其他几个游戏的枚举了，还以为已经实现了🤣

**Comment by MuXia-0326** [comment]
> > 本项目不支持米游社除原神外的其他游戏签到 如果你会java代码的话，可以参考其他项目对本项目进行拓展 如果你不会的话，可以考虑使用其他项目进行签到领取
> 
> 我看里面都有其他几个游戏的枚举了，还以为已经实现了🤣

代码参考的这个项目
https://github.com/PonKing66/genshi-helper
你可以自己改方法的入参测试看看
