### ISSUE TITLE
米游社的米游币签到任务运行失败

### ISSUE THREAD

**Issue by sev769** [wyt1215819315/autoplan#74]
但原神签到福利可以运行。我试过新建任务也不行，请问下是什么原因呢~
![image](https://user-images.githubusercontent.com/58086895/185589870-0816f97c-229c-454c-ae09-fb4c622a5353.png)

**Comment by MuXia-0326** [comment]
了解，等待后续版本更新

**Comment by MuXia-0326** [comment]
[2.7](https://github.com/wyt1215819315/autoplan/releases/tag/v2.7)版本，解决此问题
