### ISSUE TITLE
米游社账号无法添加

### ISSUE THREAD

**Issue by jp2112352919** [wyt1215819315/autoplan#78]
已经添加的任务正常执行，尝试添加新的账号显示  连接服务器失败！

**Comment by MuXia-0326** [comment]
我这边测试是正常的

**Comment by jp2112352919** [comment]
> 我这个测试是正常的

上面说的话 好像有点问题 我之前记得打的是 已经添加的账号可以正常执行 但是无法添加新的账号 无法添加的时候显示是链接服务器失败 （我尝试在自己的网站添加与作者大大你的网站添加得到的结果都是一样的 当然 也有可能是因为我那个账户是新注册的原因所以无法添加或者其他某些不知道的原因 ）
