### ISSUE TITLE
哔哩哔哩预留的硬币数一直都是50，无法改变，导致无法投币

### ISSUE THREAD

**Issue by 2698611149** [wyt1215819315/autoplan#88]

**Comment by MuXia-0326** [comment]
最新版本修复，该问题
[v2.10](https://github.com/wyt1215819315/autoplan/releases/tag/v2.10)

**Comment by 2698611149** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
