### ISSUE TITLE
按照教程部署完2.10版后，b站提示这个，无法运行

### ISSUE THREAD

**Issue by haitecnc** [wyt1215819315/autoplan#89]
![image](https://user-images.githubusercontent.com/75169146/202694976-e46d1fa0-6e92-4e62-b95e-feb25fcd12a6.png)

**Comment by haitecnc** [comment]
更新了刚才打包的 最新版，还是提示这个
![image](https://user-images.githubusercontent.com/75169146/202696816-bed51b49-84a9-4212-9ef6-dd3135e07394.png)
![image](https://user-images.githubusercontent.com/75169146/202696892-e6cdf718-fa40-44d8-aa0b-b0cfa6350582.png)
![image](https://user-images.githubusercontent.com/75169146/202696930-c818cdc0-b629-4188-9e40-ca9be97d3296.png)
![image](https://user-images.githubusercontent.com/75169146/202696989-61f2cae6-1b08-4e5b-8a65-0718a231d428.png)
之前装过老版本，今天卸载了 ，换了新版，数据库也清理了重新来的

**Comment by haitecnc** [comment]
检查发现页面有500错误，但是可以注册账号，也可以设置管理员，数据库应该是可以访问的

**Comment by haitecnc** [comment]
![image](https://user-images.githubusercontent.com/75169146/202698336-243e41d9-9795-44bd-96a0-a829ee338529.png)

**Comment by MuXia-0326** [comment]
新版的b站的数据格式需要转成json的
点击转JSON按钮进行操作

**Comment by haitecnc** [comment]
大佬您好，这个报错的问题解决了，但是新增加的那个小米步数，依然提示接口错误

**Comment by mowei1600** [comment]
> 大佬您好，这个报错的问题解决了，但是新增加的那个小米步数，依然提示接口错误

你是自己打包编译的，还是下载的jar包

**Comment by haitecnc** [comment]
下载的编译包，就是那个auto build那个

**Comment by haitecnc** [comment]
![image](https://user-images.githubusercontent.com/75169146/203489150-f6cdfd09-1af9-4e3f-b185-7d7447486bc3.png)
这个位置

**Comment by mowei1600** [comment]
> 下载的编译包，就是那个auto build那个

sql执行最新的了吗，刚刚我测试过了一遍，没任何问题

**Comment by haitecnc** [comment]
。。。。 数据库之前用的当时下载的最新的，但是我现在发现你9min前又上传了一个更新的

**Comment by mowei1600** [comment]
> 。。。。 数据库之前用的当时下载的最新的，但是我现在发现你9min前又上传了一个更新的

你可以看看提交记录，只是加了一个重置任务的sql，跟这个没关系的

**Comment by haitecnc** [comment]
我是不是应该换这个最新的

**Comment by mowei1600** [comment]
> 我是不是应该换这个最新的

可以

**Comment by haitecnc** [comment]
那能把之前已经录入的b站账号信息备份出来吗？

**Comment by mowei1600** [comment]
> 那能把之前已经录入的b站账号信息备份出来吗？

你也可以只执行小米运动的sql

**Comment by haitecnc** [comment]
大佬，我。。。 说起来蛮不好意思的，我真不会。。。 我只是按照您写的教程一步步架设起来了，但教程里面没有的其他就。。。

**Comment by mowei1600** [comment]
> 大佬，我。。。 说起来蛮不好意思的，我真不会。。。 我只是按照您写的教程一步步架设起来了，但教程里面没有的其他就。。。

那你备份一下，然后执行新的，再把备份的导入进去

**Comment by haitecnc** [comment]
全库备份是吗 大佬

**Comment by mowei1600** [comment]
> 全库备份是吗 大佬

嗯
